sudo: required # tells Travis we need super-user level permission in order to run Docker builds correctly
services:
  - docker # Travis will automatically install a Docker copy into our running container

before_install: # a series of instruction to run before we run our project
  - docker build -t arouzaud/docker-react -f Dockerfile.dev .

script: #contains all commands supposed to be executed so the test will be executed.
  # Travis CI will watch the output of each of these commands, to see if the test succeeds or fails
  - docker run -e CI=true arouzaud/docker-react npm run test # the -e CI=true is here so the npm run test runs and then exits back to the command line, so Travis is not stuck there forever
